[package]
name = "wuwa-launcher"
description = "WuWa Launcher written in Rust"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
relm4.workspace = true
